exp_manager:
  checkpoint_callback_params:
    mode: min
    monitor: val_wer
  create_checkpoint_callback: true
  create_tensorboard_logger: true
  create_wandb_logger: false
  exp_dir: null
  name: QuartzNet15x5
  wandb_logger_kwargs:
    name: null
    project: null
model:
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 128
    num_classes: 34
    vocabulary: &id001
    - "\u0439"
    - "\u0446"
    - "\u0443"
    - "\u043A"
    - "\u0435"
    - "\u043D"
    - "\u0433"
    - "\u0448"
    - "\u0449"
    - "\u0437"
    - "\u0445"
    - "\u044A"
    - "\u0444"
    - "\u044B"
    - "\u0432"
    - "\u0430"
    - "\u043F"
    - "\u0440"
    - "\u043E"
    - "\u043B"
    - "\u0434"
    - "\u0436"
    - "\u044D"
    - "\u0451"
    - "\u044F"
    - "\u0447"
    - "\u0441"
    - "\u043C"
    - "\u0438"
    - "\u0442"
    - "\u044C"
    - "\u0431"
    - "\u044E"
    - ' '
  dropout: 0.0
  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    activation: relu
    conv_mask: true
    feat_in: 64
    jasper:
    - dilation:
      - 1
      dropout: 0.0
      filters: 64
      kernel:
      - 33
      repeat: 1
      residual: false
      separable: true
      stride:
      - 2
    - dilation:
      - 1
      dropout: 0.0
      filters: 64
      kernel:
      - 33
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 128
      kernel:
      - 51
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 2
      dropout: 0.0
      filters: 128
      kernel:
      - 87
      repeat: 1
      residual: false
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 128
      kernel:
      - 1
      repeat: 1
      residual: false
      stride:
      - 1
  labels: *id001
  optim:
    betas:
    - 0.8
    - 0.5
    lr: 0.01
    name: novograd
    sched:
      last_epoch: -1
      min_lr: 0.0
      name: CosineAnnealing
      warmup_ratio: null
      warmup_steps: null
    weight_decay: 0.001
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    dither: 1.0e-05
    features: 64
    frame_splicing: 1
    n_fft: 512
    normalize: per_feature
    sample_rate: 16000
    window: hann
    window_size: 0.02
    window_stride: 0.01
  repeat: 5
  sample_rate: 24000
  separable: true
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    rect_freq: 50
    rect_masks: 5
    rect_time: 120
  test_ds:
    batch_size: 32
    labels: *id001
    manifest_filepath: test_manifest.json
    normalize_transcripts: false
    num_workers: 8
    pin_memory: true
    sample_rate: 24000
    shuffle: false
  train_ds:
    batch_size: 1024
    bucketing_batch_size: null
    bucketing_strategy: synced_randomized
    is_tarred: false
    labels: *id001
    manifest_filepath: train_manifest_big.json
    max_duration: 16.7
    normalize_transcripts: false
    num_workers: 8
    pin_memory: true
    sample_rate: 24000
    shuffle: true
    shuffle_n: 2048
    tarred_audio_filepaths: null
    trim_silence: true
  validation_ds:
    batch_size: 32
    labels: *id001
    manifest_filepath: test_manifest.json
    normalize_transcripts: false
    num_workers: 8
    pin_memory: true
    sample_rate: 24000
    shuffle: false
name: QuartzNet5x2
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  benchmark: false
  devices: 1
  enable_checkpointing: false
  log_every_n_steps: 1
  logger: false
  max_epochs: 100
  max_steps: -1
  num_nodes: 1
  strategy: null
  val_check_interval: 1.0
